using BCrypt.Net;
var users = new[]
{
    ("WhatsAppSales-Manager","whatsappsales-manager","WhatsappSalesManager@123"),
    ("Merchandiser-Manager","merchandiser-manager","MerchandiserManager@123"),
    ("CustomerAccounts-Manager","customeraccounts-manager","CustomerAccountsManager@123"),
    ("HOD","hod","Hod@123"),
    ("Admin","admin","Admin@123"),
    ("AARTI WS","aarti","Aarti@123"),
    ("VIKAS SINGH","vikassingh","Vikassingh@123"),
    ("J.P","jp","Jp@123"),
    ("RAHUL RAI","rahulrai","Rahulrai@123"),
    ("POOJA","pooja","Pooja@123"),
    ("RAJEEV KUMAR","rajeevkumar","Rajeevkumar@123"),
    ("MANISHA","manisha","Manisha@123"),
    ("KARAN","karan","Karan@123"),
    ("PAWAN BHATIA","pawanbhatia","Pawanbhatia@123"),
    ("KAMAL","kamal","Kamal@123"),
    ("SARITA","sarita","Sarita@123"),
    ("MONU KASHYAP","monukashyap","Monukashyap@123"),
    ("GAGAN","gagan","Gagan@123"),
    ("SHIKHA","shikha","Shikha@123"),
    ("RAJ KUMAR","rajkumar","Rajkumar@123"),
    ("SANDEEP","sandeep","Sandeep@123"),
    ("NEHA","neha","Neha@123"),
    ("PRIYANKA GUPTA","priyankagupta","Priyankagupta@123"),
    ("SHASHANK","shashank","Shashank@123"),
    ("ANJALI","anjali","Anjali@123"),
    ("BALGOVIND","balgovind","Balgovind@123"),
    ("SAPNA","sapna","Sapna@123"),
    ("KIRTI","kirti","Kirti@123"),
    ("AARTI CA","aarti.ca","Aarti@123"),
    ("PINKI","pinki","Pinki@123"),
};
foreach(var (name,email,pw) in users)
    Console.WriteLine($"{name}|{email}@tejoo.com|{BCrypt.Net.BCrypt.HashPassword(pw)}");
